// TERCEIRA AULA (MOVENDO ELEMENTOS)
/*
    "Nó" é o nome tecnico dos elementos no DOM.
    PODEMOS ACESSAR TODOS OS ELEMENTOS A PARTIR DE DOCUMENT.BODY
    A PARTIR DELE PODEMOS ACESSAR OS ELEMENTOS(CHILDNODES)
    E DEPOIS ACESSANDO AS PROPRIEDADES/ATRIBUTOS COM LEAFNODES
    PODEMOS ATIVAR UMA PROPRIEDADE QUE CHEGA O VALOR OU RETORNO DE UM ELEMENTO.
*/

console.log(document.body)
console.log(document.body.childNodes[1].childNodes[3].innertext)